repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog Secret Scanner
        entry: bash -c 'git diff --cached --name-only | xargs -I {} trufflehog filesystem {} --fail --no-verification 2>/dev/null || trufflehog filesystem . --since-commit HEAD --fail --no-verification'
        language: system
        pass_filenames: false
        stages: [pre-commit]